version: '3.8'
services:

  backend:
    build:
      context: backend
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./backend/src:/app/src
      - ./backend/prisma:/app/prisma
      - ./backend/package.json:/app/package.json
      - ./backend/yarn.lock:/app/yarn.lock
    environment:
      - DATABASE_URL=postgresql://admin:testing@db:5432/campus_restaurant_db

  frontend:
    build: 
      context: frontend
    restart: always
    ports:
      - 80:6116
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/package.json:/app/package.json
      - ./frontend/yarn.lock:/app/yarn.lock
      - ./frontend/index.html:/app/index.html
      - ./frontend/vite.config.ts:/app/vite.config.ts

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=testing
      - POSTGRES_DB=campus_restaurant_db
    volumes:
      - ./data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 5555:8080
